export * from "./IUtenteRepository";
export * from "./IPazienteRepository";
export * from "./IMedicoRepository";
export * from "./IRefertoRepository";
export * from "./IAuditLogRepository";
export * from "./IPasswordHasher";
export * from "./IUuidGenerator";
export * from "./ITokenManager";
export * from "./IGestoreTransazioni";
